IssueTracker/Models/Project.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IssueTracker.Models
{
    public class Project
    {
        public int Id { get; set; }

        #region Parents / Children
        public virtual ICollection<Ticket> Tickets { get; set; }

        public virtual ICollection<ApplicationUser> Users { get; set; }
        #endregion

        #region Actual Properties
        public string Name { get; set; }

        public DateTime Created { get; set; }

        public bool IsArchived { get; set; }

        #endregion

        #region Constructor
        public Project()
        {
            Tickets = new HashSet<Ticket>();
            Users = new HashSet<ApplicationUser>();
        }
        #endregion
    }
}

IssueTracker/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using IssueTracker.Helpers;
using IssueTracker.Models;
using IssueTracker.ViewModels;
using Amazon.DynamoDBv2;

namespace IssueTracker.Controllers
{
    [Authorize]
    public class ProjectsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private UserHelper userHelper = new UserHelper();
        private RolesHelper rolesHelper = new RolesHelper();
        private ProjectHelper projectHelper = new ProjectHelper();


        // GET: Projects
        public ActionResult Index()
        {
            return View(db.Projects.ToList());
        }

        // GET: Projects/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }

            ViewBag.TicketPriorityId = new SelectList(db.TicketPriorities, "Id", "Name");
            ViewBag.TicketTypeId = new SelectList(db.TicketTypes, "Id", "Name");

            return View(project);
        }

        // GET: Projects/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public ActionResult Create([Bind(Include = "Id,Name")] Project project)
        {
            if (ModelState.IsValid)
            {
                project.Created = DateTime.Now;
                project.IsArchived = false;
                db.Projects.Add(project);
                db.SaveChanges();
                projectHelper.AddUserToProject(User.Identity.GetUserId(), project.Id);
                return RedirectToAction("Index");
            }

            return View(project);
        }
        
        public ActionResult ProjectWizard()
        {
            ViewBag.ProjectManagerId = new SelectList(rolesHelper.UsersInRole("Project Manager" ), "Id", "FullName");
            ViewBag.DeveloperIds = new MultiSelectList(rolesHelper.UsersInRole("Developer"), "Id", "FullName");
            ViewBag.SubmitterIds = new MultiSelectList(rolesHelper.UsersInRole("Submitter"), "Id", "FullName");
            ViewBag.Errors = "";
            var model = new ProjectWizardVM();

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ProjectWizard(ProjectWizardVM model)
        {
            #region Fail Cases
            ViewBag.Erros = "";
            if(model.ProjectManagerId == null)
            {
                ViewBag.Errors += "<p>Please select a Project Manger.</p>";
            }
            if(model.DeveloperIds.Count == 0)
            {
                ViewBag.Erros += "<p>Please select at least one Developer.</p>";
            }
            if(model.SubmitterIds.Count == 0)
            {
                ViewBag.Error += "<p>Please select at least one Submitter.</p>";
            }
            
            #endregion

            if (ModelState.IsValid)
            {
                Project project = new Project();
                project.Name = model.Name;
                project.Created = DateTime.Now;
                project.IsArchived = false;
                db.Projects.Add(project);
                db.SaveChanges();
                projectHelper.AddUserToProject(User.Identity.GetUserId(), project.Id);

                projectHelper.AddUserToProject(model.ProjectManagerId, project.Id);
                foreach(var userId in model.DeveloperIds)
                {
                    projectHelper.AddUserToProject(userId, project.Id);
                }
                foreach (var userId in model.SubmitterIds)
                {
                    projectHelper.AddUserToProject(userId, project.Id);
                }

                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.ProjectManagerId = new SelectList(rolesHelper.UsersInRole("Project Manager"), "Id", "FullName");
                ViewBag.DeveloperIds = new MultiSelectList(rolesHelper.UsersInRole("Developer"), "Id", "FullName");
                ViewBag.SubmitterIds = new MultiSelectList(rolesHelper.UsersInRole("Submitter"), "Id", "FullName");
                return View(model);
            }
        }


        // GET: Projects/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public ActionResult Edit([Bind(Include = "Id,Name,Created,IsArchived")] Project project)
        {
            if (ModelState.IsValid)
            {
                db.Entry(project).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(project);
        }

        // GET: Projects/Delete/5
        
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // POST: Projects/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Project project = db.Projects.Find(id);
        //    db.Projects.Remove(project);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IssueTracker/Views/Projects/Create.cshtml
@model IssueTracker.Models.Project

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Project</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Created, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Created, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsArchived, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsArchived)
                    @Html.ValidationMessageFor(model => model.IsArchived, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

IssueTracker/Views/Projects/Delete.cshtml
@model IssueTracker.Models.Project

@{
    ViewBag.Title = "Delete";
}
[Authenticate]

<h2>Delete</h2>
@if (User.IsInRole("Admin") || (User.IsInRole("Project Manager")))
{
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Project</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Created)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Created)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.IsArchived)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.IsArchived)
            </dd>

        </dl>

        }

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>

IssueTracker/Views/Projects/Details.cshtml
@using Microsoft.AspNet.Identity;
@using IssueTracker.Helpers;
@model IssueTracker.Models.Project

@{
    ViewBag.Title = "Details";
    var projectHelper = new ProjectHelper();
    var rolesHelper = new RolesHelper();
    var ticketManager = new TicketManager();
}
<title>Project Details - TrackIT | Beth Olmo</title>
<body>
    <div class="container">
        <div class="page-inner">
            <div class="col-md-4">
                <div class="card card-dark bg-primary-gradient">
                    <div class="card-body pb-lg-0">
                        <div class="h1 fw-bold float-right"></div>
                        <h1 class="align-middle mb-5">Project Details</h1>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <div class="col">
                            <div class="row"><h2>Name: @Html.DisplayFor(model => model.Name) </h2></div>
                            <div class="row"><h3>Created: @Html.DisplayFor(model => model.Created)</h3></div>
                            <div class="row">
                                @if (Model.IsArchived)
                                {
                                    <h5>ARCHIVED</h5>
                                }
                                else
                                {
                                    <p></p>
                                }
                            </div>
                            <br />

                            @if (User.IsInRole("Submitter"))
                            {
                                using (Html.BeginForm("Create", "Tickets", FormMethod.Post))
                                {
                                    @Html.AntiForgeryToken()

                                    <div class="form-horizontal">
                                        <h3>Add a New Ticket</h3>
                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                        @Html.Hidden("ProjectId", Model.Id)

                                        <div class="form-group">
                                            @Html.Label("Ticket Priority", "TicketPriorityId", htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.DropDownList("TicketPriorityId", null, htmlAttributes: new { @class = "form-control" })
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            @Html.Label("Ticket Type", "TicketTypeId", htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.DropDownList("TicketTypeId", null, htmlAttributes: new { @class = "form-control" })
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            @Html.Label("Issue", htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.Editor("Issue", new { htmlAttributes = new { @class = "form-control" } })
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            @Html.Label("Issue Description", htmlAttributes: new { @class = "control-label col-md-2" })

                                            @Html.TextArea("IssueDescription", htmlAttributes: new { @class = "textarea form-control" })

                                        </div>
                                        <div class="form-group">
                                            <div class="col-md-offset-2 col-md-10">
                                                <input type="submit" value="Create" class="btn btn-success mr-5" />
                                            </div>
                                        </div>
                                    </div>
                                }
                            }
                            <br />
                            <hr />
                            <div class="row mt-5"><h2>Tickets</h2></div>
                            <br />
                            <div class="row mb-xl-5">
                                <table class="table" id="ticketTable">
                                    <thead>
                                        <tr>
                                            <th>
                                                Issue
                                            </th>
                                            <th>
                                                Priority
                                            </th>
                                            <th>
                                                Status
                                            </th>
                                            <th></th>
                                        </tr>
                                    </thead>

                                    <tbody>
                                        @foreach (var ticket in Model.Tickets)
                                        {
                                            <tr>
                                                <td>
                                                    @Html.DisplayFor(modelItem => ticket.Issue)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => ticket.TicketPriority.Name)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => ticket.TicketStatus.Name)
                                                </td>
                                                <td>
                                                    @Html.ActionLink("Details", "Dashboard", "Tickets", new { id = ticket.Id }, null)
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                            <br />
                            <a class="btn btn-success mr-2" href=@Url.Action("Edit", "Projects", new { Model.Id })><span class="btn-label"></span>Edit Project</a>
                            <a class="btn btn-warning mr-2" href=@Url.Action("Index", "Home")><span class="btn-label"></span>Dashboard</a>
                            <a class="btn btn-danger" href=@Url.Action("Index", "Projects")><span class="btn-label"></span>All Projects</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
@section scripts {

    <script>$('#ticketTable').dataTable({ responsive: true });</script>
}
<footer class="footer">

    <div class="container-fluid">
        <img src="~/Images/TrackIT1.1Light100x40.png" />
        <div class="copyright ml-auto">
            <p>&copy; @DateTime.Now.Year - <a href="//betholmo-portfolio.netlify.app/" target="_blank">Beth Olmo</a></p>
        </div>
    </div>
</footer>

IssueTracker/Views/Projects/Edit.cshtml
@model IssueTracker.Models.Project

@{
    ViewBag.Title = "Edit";
}
<title>Edit Project - TrackIT | Beth Olmo</title>
<body>
    <div class="container">
        <div class="page-inner">
            <div class="col-md-4">
                <div class="card card-dark bg-primary-gradient">
                    <div class="card-body pb-lg-0">
                        <div class="h1 fw-bold float-right"></div>
                        <h1 class="align-middle mb-5">Edit Project</h1>
                    </div>
                </div>
                <div class="card">
                    <div class="card-body">
                        @if (User.IsInRole("Admin") || (User.IsInRole("Project Manager")))
                        {
                            using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()

                                <div class="form-horizontal">

                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    @Html.HiddenFor(model => model.Id)
                                    @Html.HiddenFor(model => model.Created)

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        @Html.Label("Archive?", htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            <div class="checkbox">
                                                @Html.EditorFor(model => model.IsArchived)
                                                @Html.ValidationMessageFor(model => model.IsArchived, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="col-md-offset-2 col-md-10">
                                            <input type="submit" value="Save" class="btn btn-success mr-1" />
                                            <a class="btn btn-warning mr-1" href=@Url.Action("Index", "Home")><span class="btn-label"></span>Dashboard</a>
                                            <a class="btn btn-danger" href=@Url.Action("Index", "Projects")><span class="btn-label"></span>All Projects</a>
                                        </div>
                                    </div>
                                </div>
                            }
                        }
                </div>
            </div>
        </div>
    </div>
    </div>
</body>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<footer class="footer">

    <div class="container-fluid">
        <img src="~/Images/TrackIT1.1Light100x40.png" />
        <div class="copyright ml-auto">
            <p>&copy; @DateTime.Now.Year - <a href="//betholmo-portfolio.netlify.app/" target="_blank">Beth Olmo</a></p>
        </div>
    </div>
</footer>

IssueTracker/Views/Projects/Index.cshtml
@using Microsoft.AspNet.Identity;
@using IssueTracker.Helpers;
@model IEnumerable<IssueTracker.Models.Project>

@{
    ViewBag.Title = "Index";
    var projectHelper = new ProjectHelper();

}

<title>All Projects - TrackIT | Beth Olmo</title>
<div class="container">
    <div class="page-inner">
        <div class="col-md-4">
            <div class="card card-dark bg-primary-gradient">
                <div class="card-body pb-lg-0">
                    <div class="h1 fw-bold float-right"></div>
                    <h1 class="align-middle mb-5">All Projects</h1>
                </div>
            </div>
        </div>
        <div class="col-10">
            <div class="card">
                <div class="card-body">
                    <br />
                    <table class="table" id="projectsTable">
                        <thead>
                            <tr>
                                <th>
                                    Project Name
                                </th>
                                <th>
                                    Created On
                                </th>
                                <th>
                                    Archived?
                                </th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {

                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Name)
                                    </td>
                                    <td>
                                        @Html.DisplayName(item.Created.ToString("MM/dd/yyyy"))
                                    </td>
                                    @if (item.IsArchived)
                                    {
                                        <td>
                                            <p>Archived</p>
                                        </td>
                                    }
                                    else
                                    {
                                        <td>
                                        </td>
                                    }

                                    @if (User.IsInRole("Admin") || (User.IsInRole("Project Manager")))
                                    {
                                        <td>
                                            @Html.ActionLink("Edit", "Edit", new { id = item.Id })

                                        </td>
                                    }

                                    @if (projectHelper.IsUserOnProject(User.Identity.GetUserId(), item.Id))
                                    {
                                        <td>
                                            @Html.ActionLink("Details", "Details", new { id = item.Id })
                                        </td>
                                    }

                                </tr>
                            }
                        </tbody>
                    </table>
                    <br />
                    <hr />
                    @if (User.IsInRole("Admin"))
                    {
                        <a class="btn btn-success mr-2" href=@Url.Action("ProjectWizard", "Projects")><span class="btn-label"></span>Create New</a>
                    }
                    <a class="btn btn-warning" href=@Url.Action("Index", "Home")><span class="btn-label"></span>Dashboard</a>
                </div>
            </div>
        </div>
    </div>
</div>
<footer class="footer">
    <div class="container-fluid">
        <img src="~/Images/TrackIT1.1Light100x40.png" />
        <div class="copyright ml-auto">
            <p>&copy; @DateTime.Now.Year - <a href="//betholmo-portfolio.netlify.app/" target="_blank">Beth Olmo</a></p>
        </div>
    </div>
</footer>
@section scripts {
    <script>
        $('#projectsTable').dataTable({});
    </script>
}

IssueTracker/Views/Projects/ProjectWizard.cshtml
@model IssueTracker.ViewModels.ProjectWizardVM
@{
    ViewBag.Title = "ProjectWizard";
}
<title>New Project - TrackIT | Beth Olmo</title>
<body>
    <div class="container">
        <div class="page-inner">

            @if (ViewBag.Errors.Length > 0)
            {
                <span class="text-danger">
                    @Html.Raw(ViewBag.Errors)
                </span>
            }
            else
            {
                <div class="col-md-4">
                    <div class="card card-dark bg-primary-gradient">
                        <div class="card-body pb-lg-0">
                            <div class="h1 fw-bold float-right"></div>
                            <h1 class="align-middle mb-5">New Project</h1>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-body">

                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()

                                if (User.IsInRole("Admin") || (User.IsInRole("Project Manager")))
                                {
                                    <div class="form-horizontal">
                                        <hr />
                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                        <div class="form-group">
                                            @Html.Label("Project Name", htmlAttributes: new { @class = "control-label" })
                                            <div class="col-md-10">
                                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            @Html.Label("Project Manager", htmlAttributes: new { @class = "control-label" })
                                            <div class="col-md-10">
                                                @Html.DropDownList("ProjectManagerId", null, htmlAttributes: new { @class = "form-control" })
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            @Html.Label("Developer", htmlAttributes: new { @class = "control-label" })
                                            <div class="col-md-10">
                                                @Html.ListBox("DeveloperIds", null, htmlAttributes: new { @class = "form-control" })
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            @Html.Label("Ticket Submitter", htmlAttributes: new { @class = "control-label" })
                                            <div class="col-md-10">
                                                @Html.ListBox("SubmitterIds", null, htmlAttributes: new { @class = "form-control" })
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-offset-2 col-md-10">
                                                <input type="submit" value="Create" class="btn btn-success mr-2" />
                                                <a class="btn btn-warning" href=@Url.Action("Index", "Home")><span class="btn-label"></span>Dashboard</a>
                                            </div>
                                        </div>
                                    </div>
                                }
                                else
                                {
                                    <h3 class="mt-xl-5">You must be logged in as an Admin or Project Manager to access the Project Wizard.</h3>
                                }
                            }
                        </div>
                    </div>
                </div>

            }



        </div>
    </div>
</body>
<footer class="footer">

    <div class="container-fluid">
        <img src="~/Images/TrackIT1.1Light100x40.png" />
        <div class="copyright ml-auto">
            <p>&copy; @DateTime.Now.Year - <a href="//betholmo-portfolio.netlify.app/" target="_blank">Beth Olmo</a></p>
        </div>
    </div>
</footer>