IssueTracker/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IssueTracker.Models;
using Microsoft.AspNet.Identity;

namespace IssueTracker.Controllers
{
    [Authorize]
    
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            return View(db.Users.Find(User.Identity.GetUserId()));
        }
        [AllowAnonymous]
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

IssueTracker/Controllers/UsersController.cs
using IssueTracker.Helpers;
using IssueTracker.Models;
using Microsoft.Owin.Security.Provider;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IssueTracker.Controllers
{
    [Authorize]
    public class UsersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private RolesHelper roleHelper = new RolesHelper();

        

        // GET: Users
        public ActionResult Index()
        {
            return View(db.Users.ToList());
        }
        
        public ActionResult ManageUserRole(string id)
        {
            if(id == null)
            {
                return RedirectToAction("Index");
            }
            var userRole = roleHelper.ListUserRoles(id).FirstOrDefault();
            ViewBag.RoleName = new SelectList(db.Roles, "Name", "Name", userRole);
            return View(db.Users.Find(id));
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult ManageUserRole(string id, string roleName)
        {
            foreach (var role in roleHelper.ListUserRoles(id))
            {
                roleHelper.RemoveUserFromRole(id, role);
            }

            if(!string.IsNullOrEmpty(roleName))
            {
                roleHelper.AddUserToRole(id, roleName);
            }

            TempData["Message"] = "The user's role has been updated.";
            return RedirectToAction("Index");
        }

       

    }
}

IssueTracker/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<!DOCTYPE html>

<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>About TrackIT | Beth Olmo</title>
    <meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />


    <!-- Fonts and icons -->
    <script src="~/Scripts/webfont.min.js"></script>
    <script>
        WebFont.load({
            google: { "families": ["Lato:300,400,700,900"] },
            custom: {
                "families": ["Flaticon", "Font Awesome 5 Solid", "Font Awesome 5 Regular", "Font Awesome 5 Brands", "simple-line-icons"], urls: ['~/Content/fonts.css']
            },
            active: function () {
                sessionStorage.fonts = true;
            }
        });
    </script>

    <!-- CSS Files -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/atlantis.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <div class="page-inner">
            <div class="row mt-xl-5">
                <div class="col ml-xl-5">
                    <img src="~/Images/ITAboutD1920x900.png" />
                </div>
            </div>
        </div>
    </div>

    <script src="~/Scripts/jquery.3.2.1.min.js"></script>
    <script src="~/Scripts/jquery-ui.min.js"></script>
    <script src="~/Scripts/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>

IssueTracker/Views/Home/Index.cshtml
@using Microsoft.AspNet.Identity;
@using IssueTracker.Helpers;
@{
    ViewBag.Title = "Home Page";
    var userHelper = new UserHelper();
    var projectHelper = new ProjectHelper();
    var ticketManager = new TicketManager();

}

<title>TrackIT | Beth Olmo</title>

<div class="container">
    <div class="page-inner">
        <div class="row">
            <div class="col-md-4">
                <a href=@Url.Action("Index", "Projects")>
                    <div class="card card-dark bg-primary-gradient">
                        <div class="card-body pb-0">
                            <div class="h1 fw-bold float-right"></div>
                            <h1 class="align-middle mb-5">Projects</h1>
                        </div>
                    </div>
                </a>
            </div>

            <div class="col-md-4">
                <a href=@Url.Action("Index", "Tickets")>
                    <div class="card card-dark bg-secondary-gradient">
                        <div class="card-body pb-0">
                            <div class="h1 fw-bold float-right"></div>
                            <h1 class="align-middle mb-5">Tickets</h1>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-md-4">
                <a href=@Url.Action("Index", "Users")>
                    <div class="card card-dark bg-success2">
                        <div class="card-body pb-0">
                            <div class="h1 fw-bold float-right"></div>
                            <h1 class="align-middle mb-5">Users</h1>
                        </div>
                    </div>
                </a>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">My Projects</div>
                    </div>
                    <div class="card-body">
                        <table class="table" id="projectTable">
                            <thead>
                                <tr>
                                    <th>
                                        Project Name
                                    </th>
                                    <th>
                                        Created On
                                    </th>
                                    @if (User.IsInRole("Admin") || User.IsInRole("Project Manager"))
                                    {
                                        <th></th>
                                    }
                                        <th></th>
                                    </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in projectHelper.ListUserProjects(User.Identity.GetUserId()))
                                {

                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Name)
                                        </td>
                                        <td>
                                            @Html.DisplayName(item.Created.ToString("MM/dd/yyyy"))
                                        </td>



                                        @if (User.IsInRole("Admin") || User.IsInRole("Project Manager"))
                                        {
                                            <td>
                                                @Html.ActionLink("Edit", "Edit", "Projects", new { id = item.Id }, null)
                                            </td>
                                        }



                                        <td>
                                            @Html.ActionLink("Details", "Details", "Projects", new { id = item.Id }, null)
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">High Priority Tickets</div>
                    </div>
                    <div class="card-body">
                        <table class="table" id="ticketTable">
                            <thead>
                                <tr>
                                    <th>
                                        Project
                                    </th>
                                    <th>
                                        Type
                                    </th>
                                    <th>
                                        Status
                                    </th>
                                    <th>
                                        Created
                                    </th>
                                    <th>
                                        Updated
                                    </th>
                                    
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in ticketManager.MyTopTickets())
                                {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Project.Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.TicketType.Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.TicketStatus.Name)
                                    </td>
                                    <td>
                                        @Html.DisplayName(item.Created.ToString("MM/dd/yyyy"))
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Updated)
                                    </td>
                                    
                                    <td>
                                        @if (ticketManager.CanEditTicket(item.Id))
                                        {

                                            @Html.ActionLink("Edit", "Edit", "Tickets", new { id = item.Id }, null) <span>|</span>
                                            @Html.ActionLink("Details", "Dashboard", "Tickets", new { id = item.Id }, null)
                                        }

                                    </td>
                                </tr>
                                }
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>

        </div>
    </div>
</div>
@section scripts {

    <script>$('#projectTable').dataTable({ responsive: true});</script>
    <script>$('#ticketTable').dataTable({ responsive: true });</script>
}
<footer class="footer">

    <div class="container-fluid">
        <div class="row" style="width: 100%;">
            <div class="col">
                <img src="~/Images/TrackIT1.1Light100x40.png" />
            </div>
            <div class="col">
                <div class="text-center">
                    <a class="btn btn-danger align-content-center" href=@Url.Action("Login", "Account")><span class="btn-label"></span>Log Off</a>
                </div>
            </div>
            <div class="col"><p class="text-right">&copy; @DateTime.Now.Year - <a href="//betholmo-portfolio.netlify.app/" target="_blank">Beth Olmo</a></p></div>
        </div>
        </div>
            
</footer>